ablunit

diff --git a/.github/workflows/ci_ablunit.yml b/.github/workflows/ci_ablunit.yml
--- a/.github/workflows/ci_ablunit.yml
+++ b/.github/workflows/ci_ablunit.yml
@@ -51,6 +51,19 @@ jobs:
           [ "${{ steps.ablunit-2.outputs.failure-count }}" -eq 0 ] || (echo "expected failure-count=0, got ${{ steps.ablunit-2.outputs.failure-count }}" && exit 1)
           [ "${{ steps.ablunit-2.outputs.skipped-count }}" -eq 1 ] || (echo "expected skipped-count=1, got ${{ steps.ablunit-2.outputs.skipped-count }}" && exit 1)
 
+      - name: ablunit-3
+        id: ablunit-3
+        uses: ./ablunit
+        with:
+          working-directory: ablunit/test/test3
+      - name: test-3
+        shell: bash
+        run: |
+          [ "${{ steps.ablunit-3.outputs.test-count }}" -eq 1 ] || (echo "expected test-count=1, got ${{ steps.ablunit-3.outputs.test-count }}" && exit 1)
+          [ "${{ steps.ablunit-3.outputs.error-count }}" -eq 0 ] || (echo "expected error-count=0, got ${{ steps.ablunit-3.outputs.error-count }}" && exit 1)
+          [ "${{ steps.ablunit-3.outputs.failure-count }}" -eq 0 ] || (echo "expected failure-count=0, got ${{ steps.ablunit-3.outputs.failure-count }}" && exit 1)
+          [ "${{ steps.ablunit-3.outputs.skipped-count }}" -eq 0 ] || (echo "expected skipped-count=0, got ${{ steps.ablunit-3.outputs.skipped-count }}" && exit 1)
+
       - name: pre-merge-validation
         shell: bash
         run: ./.github/workflows/pre_merge_validation.sh ablunit
