compile

diff --git a/.github/workflows/ci_compile.yml b/.github/workflows/ci_compile.yml
--- a/.github/workflows/ci_compile.yml
+++ b/.github/workflows/ci_compile.yml
@@ -71,7 +71,7 @@ jobs:
         run: |
           echo "steps.compile-2.outputs.files-compiled=${{ steps.compile-2.outputs.files-compiled }}"
           RCODE_COUNT=$(find rcode -name "*.r" | wc -l)
-          [ "$RCODE_COUNT" -eq 2 ] || (echo "::error::Expected rcode count=1 but got $RCODE_COUNT" && exit 1)
+          [ "$RCODE_COUNT" -eq 2 ] || (echo "::error::Expected rcode count=2 but got $RCODE_COUNT" && exit 1)
           find . -name "*.r"
           [ -f "rcode/src/com/org/source_class.r" ] || (echo "::error::Expected compiled file rcode/src/com/org/source_class.r but it was not found" && exit 1)
           [ -f "rcode/test/com/org/source_classTest.r" ] || (echo "::error::Expected compiled file rcode/test/com/org/source_class.r but it was not found" && exit 1)
