compile failure test

diff --git a/.github/workflows/ci_compile.yml b/.github/workflows/ci_compile.yml
--- a/.github/workflows/ci_compile.yml
+++ b/.github/workflows/ci_compile.yml
@@ -98,6 +98,22 @@ jobs:
           [ "${{ steps.compile-4.outputs.compile-errors }}" -eq 1 ] || (echo "::error::Expected compile-errors=1 but got ${{ steps.compile-4.outputs.compile-errors }}" && exit 1)
           find . -name "*.r" -delete
 
+      ## compile failure stops build by default
+      - name: compile-5
+        id: compile-5
+        uses: ./compile
+        continue-on-error: true
+        with:
+          working-directory: compile/test/test5
+      - name: test-5
+        id: test-5
+        shell: bash
+        run: |
+          [ "${{ steps.compile-5.outcome }}" = "failure" ] || (echo "::error::Expected compile-5 outcome 'failure' but got '${{ steps.compile-5.outcome}}'" && exit 1)
+          [ "${{ steps.compile-5.outputs.files-compiled }}" -eq 2 ] || (echo "::error::Expected files-compiled=2 but got ${{ steps.compile-5.outputs.files-compiled }}" && exit 1)
+          [ "${{ steps.compile-5.outputs.compile-errors }}" -eq 1 ] || (echo "::error::Expected compile-errors=1 but got ${{ steps.compile-5.outputs.compile-errors }}" && exit 1)
+          find . -name "*.r" -delete
+
       - name: pre-merge-validation
         shell: bash
         run: ./.github/workflows/pre_merge_validation.sh compile
