indent test

diff --git a/.github/workflows/ci_documentation.yml b/.github/workflows/ci_documentation.yml
--- a/.github/workflows/ci_documentation.yml
+++ b/.github/workflows/ci_documentation.yml
@@ -18,13 +18,33 @@ jobs:
             license: ${{ secrets.PROGRESS_CFG_LICENSE }}
             working-directory: documentation/test/test1
             artifact-name: documentation-test-1
-            # pct-buildDir: .
             pct-encoding: utf8
       - name: test-1
         shell: bash
         working-directory: documentation/test/test1
         run: |
           [ -f "documentation.json" ] || (echo "::error::Expected documentation file documentation.json but it was not found" && exit 1)
+
+      - name: pre-merge-validation
+        shell: bash
+        run: ./.github/workflows/pre_merge_validation.sh documentation
+
+      ## a documentation test with indent
+      - name: documentation-2
+        uses: ./documentation
+        with:
+            working-directory: documentation/test/test1
+            skip-compile: true
+            artifact-name: documentation-test-2
+            pct-indent: true
+            pct-destFile: documentation-2.json
+      - name: test-2
+        shell: bash
+        working-directory: documentation/test/test1
+        run: |
+          [ -f "documentation-2.json" ] || (echo "::error::Expected documentation file documentation-2.json but it was not found" && exit 1)
+          NUM_LINES=$(wc -l < documentation-2.json)
+          [ "$NUM_LINES" -gt 1 ] || (echo "::error::Expected num lines > 1 but got $NUM_LINES" && exit 1)
 
       - name: pre-merge-validation
         shell: bash
