separate download-ade step

diff --git a/.github/workflows/ci_setup.yml b/.github/workflows/ci_setup.yml
--- a/.github/workflows/ci_setup.yml
+++ b/.github/workflows/ci_setup.yml
@@ -52,12 +52,12 @@ jobs:
           exit 1
 
       ## setup a second version with a different DLC, no license provided so setup succeeds but _progres fails to execute
-      - name: setup-abl-3A
+      - name: setup-abl-3
         uses: ./setup
         with:
           version: 12.8.1
           cache-key: 'null'
-      - name: test-3A
+      - name: test-3
         shell: bash
         run: |
           [ "$(awk '{print $3}' "$DLC/version")" = "12.8.1" ] || (echo "::error::could not set abl version to 12.8.1" && exit 1)
@@ -109,7 +109,9 @@ jobs:
       - name: test-6
         shell: bash
         run: |
-          [ -f "$DLC/src/ablunit/ABLUnitCore.p" ] || (echo "::error::expected ABLUnitCore.p file in ADE source" && exit 1)
+          ls -al "$DLC/src"
+          ls -al "$DLC/src/ablunit"
+          [ -f "$DLC/src/ablunit/ABLUnitCore.p" ] || (echo "::error::expected file $DLC/src/ablunit/ABLUnitCore.p to exist" && exit 1)
 
       ## setup using cache with implicit key
       - name: setup-abl-7A
